modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/starfish-studios/Naturalist/issues"
license="MIT"

[[mods]]
modId="naturalist"
version="${version}"
displayName="Naturalist"
authors="Starfish Studios"
displayURL="https://www.curseforge.com/minecraft/mc-mods/naturalist"
description='''
Enhances the overworld by adding new wildlife with unique behavior!
'''
logoFile="icon.png"

[[mixins]]
config="naturalist.mixins.json"

[[dependencies.naturalist]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.naturalist]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.naturalist]]
modId="geckolib"
type="required"
versionRange="[4.8.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.naturalist]]
modId="lambdynlights"
type="optional"
versionRange="[4.8,)"
ordering="NONE"
side="CLIENT"
